### ISSUE TITLE
fluid.py shows an error

### ISSUE THREAD

**Issue by misael-tup** [j-jith/pythermophy#2]
Hi. I hope you find well.

When I try to run an example (after installation) iit shows:

 runfile('../prueba_spyder.py', wdir='C:/Users/misab/pythermophy')
Traceback (most recent call last):

  File "..\prueba_spyder.py", line 17, in <module>
    fluid = pt.Fluid.init_from_file('fluids\CO2.yaml')

  File "D:\Apps\Anaconda\lib\site-packages\pythermophy-0.1-py3.8.egg\pythermophy\fluid.py", line 103, in init_from_file
    valid = inst.is_valid()

  File "D:\Apps\Anaconda\lib\site-packages\pythermophy-0.1-py3.8.egg\pythermophy\fluid.py", line 47, in is_valid
    if not isinstance(self.name, basestring):

NameError: name 'basestring' is not defined

Any suggestions? Thank you so much!

**Comment by j-jith** [comment]
Thanks for pointing this out. I'm not sure why I used 'basestring' instead of 'str' in that line. You can fix this by directly replacing 'basestring' with 'str' in line 47 of fluid.py. I've already made a commit to fix this issue.
